services:
  server:
    container_name: quiz_dev_api
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm run dev"
networks:
  default:
    name: quiz_dev
